<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Download extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Download_model');
        $this->load->model('Log_model');
			$this->load->helper('download');
        $this->load->library('form_validation');
        chek_session();
    }

   public function index() {
	$data['data1']=$this->Download_model->get_all_files();


        $this->template->display('download/tb_download_list', $data);
    }
	  
   function get_file(){
		$data1 = array(
              
              
                      'crud' => "mendownload",
                      'menu' => "file",
            'datetime' => date("Y-m-d H:i:s"),
   

                'user' => 	$this->session->userdata('user_id'),
         
            );
      $this->Log_model->insert($data1);	
			
		$id=$this->uri->segment(3);
		$get_db=$this->Download_model->get_file_byid($id);
		$q=$get_db->row_array();
		$file=$q['file_data'];
		$path='./assets/files/'.$file;
		$data = file_get_contents($path);
		$name = $file;
		force_download($name, $data);
	       
            
	}


}

/* End of file status.php */
/* Location: ./application/controllers/status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:06:57 */
/* http://harviacode.com */