<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kirim extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Kirim_model');
        $this->load->model('Log_model');

        $this->load->library('form_validation');
        chek_session();
    }

    public function index() {
		  $id = $this->session->userdata('user_id');
				      $subi1 = $this->session->userdata('group_id');
					  $get3 =$this->db->get_where("tb_users_groups",array("user_id" =>$id))->row();
					  	$tanggal1 = $get3->group_id;
                if ($tanggal1=="2") {
					  return show_error('Harus Login sebagai sekretaris untuk mengakses halaman ini');
				}
				else{
        $kirim = $this->Kirim_model->get_all();

        $data = array(
            'kirim_data' => $kirim
        );

				$this->template->display('kirim/tb_kirim_list', $data);
				}
				
    }

    public function create() {
		
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('kirim/create_action'),
            'id' => set_value('id'),
            'status' => set_value('status'),
                   'untuk' => set_value('untuk'),
                   'isi' => set_value('isi'),
        );
        $this->template->display('kirim/tb_kirim_form', $data);
			
    }

    public function create_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
			
					
						$de = $this->input->post('untuk');
                if ($de=="sekretaris") {
            $data = array(
                'status' => "keluar",
                'isi' => $this->input->post('isi', TRUE),            
                'untuk' => "admin",  
   
     'date2' => date("Y-m-d H:i:s"),	 
				);
				    $this->Kirim_model->insert($data);
				}
				 else {
            $data = array(
                'status' => "masuk",
                'isi' => $this->input->post('isi', TRUE),            
                'untuk' => "sekretaris",  
   
     'date2' => date("Y-m-d H:i:s"),	 
				);
				    $this->Kirim_model->insert($data);
				 }

        
	
			$data1 = array(
              
              
                      'crud' => "mengirim",
                      'menu' => "pesan",
            'datetime' => date("Y-m-d H:i:s"),
          

                'user' => 	$this->session->userdata('user_id'),
         
            );

            $this->Log_model->insert($data1);
           echo $this->session->set_flashdata('Tambah', ' Berhasil Menambah data....');
            redirect(site_url('kirim'));
        }
    }


    public function _rules() {
  
        $this->form_validation->set_rules('isi', 'isi', 'trim|required');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

 function delete_mutiple() {
			$delete = $this->input->post('msg');
	if($delete>0){
			$this->Kirim_model->remove_checked();
		 echo $this->session->set_flashdata('Hapus', ' Berhasil Menghapus data....');
            redirect(site_url('kirim'));
		}
   
   else{
	    echo $this->session->set_flashdata('Hapus1', ' Tidak ada data yang diceklis....');
	       redirect(site_url('kirim'));
   }

		}


}

/* End of file status.php */
/* Location: ./application/controllers/status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:06:57 */
/* http://harviacode.com */