<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Log extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Log_model');


        chek_session();
    }

    public function index() {
          $data['ion1'] = $this->Log_model->get_transaksi();	
        $this->template->display('log/tb_log_list', $data);
    }
	
	  
    public function delete($id) {
        $row = $this->Log_model->get_by_id($id);

        if ($row) {
            $this->Log_model->delete($id);
                echo $this->session->set_flashdata('Hapus', ' Berhasil Menghapus data....');
            redirect(site_url('log'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('log'));
        }
    }

    function delete_mutiple() {
			$delete = $this->input->post('msg');
	if($delete>0){
			$this->Log_model->remove_checked();
		 echo $this->session->set_flashdata('Hapus', ' Berhasil Menghapus data....');
            redirect(site_url('log'));
		}
   
   else{
	    echo $this->session->set_flashdata('Hapus1', ' Tidak ada data yang diceklis....');
	       redirect(site_url('log'));
   }

		}

}

/* End of file status.php */
/* Location: ./application/controllers/status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:06:57 */
/* http://harviacode.com */