<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Logo extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Logo_model');


        chek_session();
    }

    public function index() {
            $ion1 = $this->Logo_model->get_all();

        $data = array(
            'ion1' => $ion1
        );

        $this->template->display('logo/tb_logo_list', $data);
    }
	
	  
    public function delete($id) {
        $row = $this->Logo_model->get_by_id($id);

        if ($row) {
            $this->Logo_model->delete($id);
                echo $this->session->set_flashdata('Hapus', ' Berhasil Menghapus data....');
            redirect(site_url('logo'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('logo'));
        }
    }
 function delete_mutiple() {
			$delete = $this->input->post('msg');
	if($delete>0){
			$this->Logo_model->remove_checked();
		 echo $this->session->set_flashdata('Hapus', ' Berhasil Menghapus data....');
            redirect(site_url('logo'));
		}
   
   else{
	    echo $this->session->set_flashdata('Hapus1', ' Tidak ada data yang diceklis....');
	       redirect(site_url('logo'));
   }

		}

    

}

/* End of file status.php */
/* Location: ./application/controllers/status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:06:57 */
/* http://harviacode.com */