<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat extends CI_Controller {

    function __construct() {
        parent::__construct();
    
		    $this->load->model('Log_model');
        $this->load->library('form_validation');
        chek_session();
    }

    public function index() {
     
				$this->template->display('surat/tb_surat_list', $data);
    }
	
	    
    public function create() {
		 $id = $this->session->userdata('user_id');
				      $subi1 = $this->session->userdata('group_id');
					  $get3 =$this->db->get_where("tb_users_groups",array("user_id" =>$id))->row();
					  	$tanggal1 = $get3->group_id;
                if ($tanggal1=="3") {
					   $data = array(
            'button' => 'Cetak',
            'action' => site_url('surat/simpan'),
            'id' => set_value('id'),
            'no' => set_value('no'),
                   'no1' => set_value('no1'),
                   'tahun' => set_value('tahun'),
				    'id_jadwal' => set_value('id_jadwal'),
                   'id_member' => set_value('id_member'),
                   'tanda' => set_value('tanda'),
                  
        );
		  $data['jadwal'] = $this->db->get_where('jadwal')->result();
				   $data['member'] = $this->db->get_where('member')->result();
				 
        $this->template->display('surat/tb_surat_form', $data);
    }
				
				else{
    return show_error('Harus Login sebagai sekretaris untuk mengakses halaman ini');} }

   

 
    public function _rules() {
        $this->form_validation->set_rules('no', 'no surat', 'trim|required|min_length[3]|max_length[3]');
        $this->form_validation->set_rules('no1', 'no surat selanjutnya', 'trim|required|min_length[3]|max_length[3]');
        $this->form_validation->set_rules('id_member', '   penerima surat', 'trim|required');
        $this->form_validation->set_rules('id_jadwal', '   nama acara', 'trim|required');
       
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
public function simpan(){
    $this->_rules();
	 if ($this->form_validation->run() == FALSE) {
             $this->create();
        } else {
	 	  $data['jadwal'] = $this->db->get_where('jadwal')->result();
		  $data['member'] = $this->db->get_where('member')->result();
        $no = $_POST['no'];
        $no1 = $_POST['no1'];
		$id_member = $_POST['id_member'];
		$id_jadwal = $_POST['id_jadwal'];
		$tanda = $_POST['tanda'];
	
	$get3 =$this->db->get_where("member",array("id" =>$id_member))->row();
	$get = $this->db->get_where("jadwal",array("id" =>$id_jadwal))->row();
	$nama = $get->nama;
	$pukul = $get->jam1;	
	$tanggal = $get->tanggal;
	$tanggal1 = $get->tanggal1;
	$tempat = $get->tempat;
if($id_member=="Kelas VII"){
	$nama1 =$id_member;
	}else if($id_member=="Kelas VIII"){
	$nama1 = $id_member;}
	else if($id_member=="Kelas IX"){
	$nama1 = $id_member;}
	else if($id_member=="Kelas VII dan VIII"){
	$nama1 = $id_member;}
	else if($id_member=="Guru"){
	$nama1 = $id_member;}
	else if($id_member=="Guru dan Karyawan"){
	$nama1 = $id_member;}
	else if($id_member=="Ketua Komite"){
	$nama1 = $id_member;}
	else if($id_member=="Anggota Komite"){
	$nama1 = $id_member;}
else{
	$nama1 = $get3->nama_member;}
	
        $this->session->set_userdata('nosession',$no);   
		 $this->session->set_userdata('no1session',$no1);
        $this->session->set_userdata('membersession',$nama1);
        $this->session->set_userdata('pukul',$pukul);
        $this->session->set_userdata('tanggal',$tanggal);	
        $this->session->set_userdata('tanggal1',$tanggal1);	
        $this->session->set_userdata('tempat',$tempat);	
		        $this->session->set_userdata('namasession',$nama);
	$data1 = array(
              
              
                      'crud' => "mencetak",
                      'menu' => "surat undangan",
            'datetime' => date("Y-m-d H:i:s"),
           

                'user' => 	$this->session->userdata('user_id'),
         
            );
      $this->Log_model->insert($data1);	
	if($tanda=="1"){
				$this->load->view('surat/pleno');}
				else if($tanda=="2"){
					$this->load->view('surat/karyawan');
				}else if($tanda=="3"){
					$this->load->view('surat/komite');
				}else{
					$this->load->view('surat/koordinasi');
				}
      
  } 
}

}

/* End of file status.php */
/* Location: ./application/controllers/status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:06:57 */
/* http://harviacode.com */