<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Grouped_model extends CI_Model {

    public $table = 'tb_users_groups';
    public $id = 'id';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table)->result();
    }
 function get_transaksi1() {


 return $this->db->query("SELECT tb_users_groups.id, tb_users_groups.group_id,tb_users_groups.user_id,tb_users.username,tb_users.email, tb_groups.name FROM tb_users_groups INNER JOIN tb_groups ON tb_users_groups.group_id=tb_groups.id INNER JOIN tb_users ON tb_users.id=tb_users_groups.user_id")->result(); }
  
    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('user_id', $q);
        $this->db->or_like('group_id', $q);

        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('user_id', $q);
        $this->db->or_like('group_id', $q);
		     
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:11:34 */
/* http://harviacode.com */