<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Member_model extends CI_Model {

    public $table = 'member';
    public $id = 'id';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table)->result();
    }

   function get_transaksi() {

        return $this->db->query("SELECT member.id,member.nama_member,member.telepon,member.alamat,member.tempat_lahir,member.tanggal_lahir,member.tempat_lahir,member.jenis_kelamin,member.pendidikan_terakhir,member.email,status.status
            FROM member INNER JOIN status ON member.id_status = status.id")->result();
			
    }
	
    function get_last_transaksi() {

        return $this->db->query("SELECT member.id,member.nama_member,member.telepon,member.alamat,member.tempat_lahir,member.tanggal_lahir,member.tempat_lahir,member.jenis_kelamin,member.pendidikan_terakhir,member.email,status.status
            FROM member INNER JOIN status ON member.id_status = status.id   ORDER BY member.id DESC LIMIT 10")->result();
    }
     


    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('nama_member', $q);
        $this->db->or_like('alamat', $q);
		 $this->db->or_like('tempat_lahir', $q);
		 		 $this->db->or_like('tanggal_lahir', $q);
		
						 		 $this->db->or_like('jenis_kelamin', $q);
								 		 $this->db->or_like('pendidikan_terakhir', $q);
										 		 $this->db->or_like('id_status', $q);
												 		 $this->db->or_like('email', $q);
        $this->db->or_like('telepon', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('nama_member', $q);
        $this->db->or_like('alamat', $q);
		       $this->db->or_like('tempat_lahir', $q);
			          $this->db->or_like('tanggal_lahir', $q);
			
							        $this->db->or_like('jenis_kelamin', $q);
									       $this->db->or_like('pendidikan_terakhir', $q);
										          $this->db->or_like('id_status', $q);
												         $this->db->or_like('email', $q);
        $this->db->or_like('telepon', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
function remove_checked() {
		$delete = $this->input->post('msg');
			for ($i=0; $i < count($delete) ; $i++) { 
				$this->db->where($this->id, $delete[$i]);
				$this->db->delete($this->table);
		
		}
	}
}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:11:34 */
/* http://harviacode.com */