<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pegawai_model extends CI_Model {

    public $table = 'tb_pegawai';
    public $id = 'id_pegawai';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table)->result();
		
    }
	function get_pegawai() {  
    $uid=$this->session->userdata('id_pegawai');	
        return $this->db->query("SELECT tb_pegawai.id_pegawai,tb_pegawai.nama_pegawai,tb_pegawai.pangkat,tb_pegawai.alamat,tb_pegawai.no_telp,tb_pegawai.email,tb_grupemail.nama1,tb_grupsms.nama,
			FROM tb_pegawai INNER JOIN tb.grupemail ON tb_pegawai.id_grup1 = tb_grupemail.id_grup1 INNER JOIN tb_grupsms ON tb_pegawai.id_grup = tb_grupsms.id_grup
			WHERE tb_pegawai.id_pegawai=$uid ORDER BY tb_pegawai.id_pegawai DESC")->result();
		  }

    function get_rows() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table)->num_rows();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pegawai', $q);
        $this->db->or_like('nama_pegawai', $q);
		        $this->db->or_like('pangkat', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_telpn', $q);
		 $this->db->or_like('id_grup', $q);
		   $this->db->or_like('email', $q);
		   $this->db->or_like('id_grup1', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pegawai', $q);
        $this->db->or_like('nama_pegawai', $q);
		        $this->db->or_like('pangkat', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_telpn', $q);
		  $this->db->or_like('id_grup', $q);
		 $this->db->or_like('email', $q);
		 	  $this->db->or_like('id_grup1', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file pegawai_model.php */
/* Location: ./application/models/pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:09:25 */
/* http://harviacode.com */