<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tanggal_model extends CI_Model {

   
    function __construct() {
        parent::__construct();
    }

   
}

/* End of file pegawai_model.php */
/* Location: ./application/models/pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:09:25 */
/* http://harviacode.com */